# Generated by Django 4.0 on 2022-02-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_counter',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='brief',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Subtitle or Selling Point'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc1',
            field=models.TextField(max_length=210, null=True, verbose_name='Description One, Short Description'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc2',
            field=models.TextField(null=True, verbose_name='Description Two'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/posts/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image2',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='images/posts/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Commentor Name')),
                ('email_address', models.EmailField(max_length=50, verbose_name='Commentor Email Address')),
                ('comments', models.TextField(verbose_name='Comment Body')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
