# Generated by Django 4.0 on 2022-03-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comments_comment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_name', models.CharField(max_length=50, verbose_name='Reply Name')),
                ('email_address', models.EmailField(max_length=50, verbose_name='Reply Email Address')),
                ('message', models.TextField(verbose_name='Reply Message Body')),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog.comment')),
            ],
            options={
                'verbose_name_plural': 'Replies',
            },
        ),
    ]
