# Generated by Django 4.0 on 2022-03-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_replies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Replies',
            new_name='Reply',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_reply',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
